// flow-typed signature: 829e704bd25a4a0493c7e1b07b3b696c
// flow-typed version: <<STUB>>/redux-saga/effects_v0.15/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga/effects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga/effects' {
  declare module.exports: any;
}
